name: Build on DockerHub
on:
  push:
    branches:
      - feature/local-auth
env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_TAG: ${{ vars.DOCKERHUB_TAG }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub $DOCKERHUB_USERNAME
        uses: docker/login-action@v1
        with:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: mbaluev/the-form-client:$DOCKERHUB_TAG