name: Build on DockerHub
on:
  push:
    branches:
      - feature/local-auth
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_TAG: ${{ vars.DOCKERHUB_TAG }}
jobs:
  display-variables:
    name: ${{ vars.DOCKERHUB_TAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        run: |
          echo "DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME"
          echo "DOCKERHUB_TOKEN: $DOCKERHUB_TOKEN"
          echo "DOCKERHUB_TAG: $DOCKERHUB_TAG"
      - name: Hello world
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ vars.DOCKERHUB_USERNAME }}
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: ./
#          push: true
#          dockerfile: ./Dockerfile
#          tags: mbaluev/the-form-client:${{ vars.DOCKERHUB_TAG }}