name: Build on DockerHub
on:
  push:
    branches:
      - feature/local-auth
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Create env file
        run: |
          touch .env
          echo TOKEN_SECRET=946cbae2-f6cd-4c35-8ac9-26b3918a69a4 >> .env
          echo TOKEN_EXPIRY=60*60*24*30 >> .env
          echo SESSION_SECRET=774e23fb-ccb2-4f04-aeda-c4e860dc0faf >> .env
          echo COOKIE_SECRET=4cb79e38-846e-46f0-89da-7377c29bec46 >> .env
          echo WHITELIST_DOMAINS=http://localhost:3002,http://localhost >> .env
          echo DATABASE_URL=postgresql://sa:@localhost:5432/the-form >> .env
          echo PORT=8081 >> .env
          cat .env
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: mbaluev/the-form-client:${{ vars.DOCKERHUB_TAG }}